name: Build MobileGlues APK (Flicker Fix)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: false
          fetch-depth: 0

      - name: Setup submodule (pakai core kamu)
        run: |
          rm -rf MobileGlues
          rm -rf .git/modules/MobileGlues || true
          git clone --depth 1 --branch main https://github.com/CihuyAkz/MobileGlues-MipmapFlickeringFix.git MobileGlues
          ls -la MobileGlues

      - name: Set date & repo name
        run: |
          echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
          echo "repository_name=\( (echo ' \){{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android NDK
        run: |
          echo "y" | sdkmanager "ndk;27.3.13750724"
          echo "ndk.dir=$ANDROID_HOME/ndk/27.3.13750724" >> local.properties

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build APK (Release)
        run: ./gradlew assembleRelease --stacktrace
        env:
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: \( {{ env.repository_name }}_ \){{ env.date_today }}_${{ github.sha }}
          path: app/build/outputs/apk/release/*.apk
          if-no-files-found: warn
